#pragma once

#define MATRIX_ROWS 9
#define MATRIX_COLS 10

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP27
#define I2C1_SCL_PIN GP28

#define WS2812_DI_PIN GP26
#define RGBLIGHT_LED_COUNT 22
#define RGBLIGHT_LIMIT_VAL 100
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD

#define ENCODER_A_PINS {GP21, GP19}
#define ENCODER_B_PINS {GP22, GP20}
